datasource:
  url: jdbc:mysql://localhost:3306/oywb_test
  jdbcUrl: jdbc:mysql://localhost:3306/oywb_test
  username: root
  password: casa
  driverClassName: com.mysql.jdbc.Driver
  testOnBorrow: true
  #validationQuery: "select 1"