datasource:
  url: jdbc:mysql://${EN_DB_ADDRESSES:120.79.70.221}:3306/oywb_test
  jdbcUrl: jdbc:mysql://${EN_DB_ADDRESSES:120.79.70.221}:3306/oywb_test
  username: ${EN_MARIADB_USER:root}
  password: ${EN_MARIADB_PASSWORD:casa}
  driverClassName: com.mysql.jdbc.Driver
  testOnBorrow: true
  #validationQuery: "select 1"